# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up --force-recreate --build --remove-orphans 

version: "3.7"

services:
  node-red:
    container_name: node_red
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data
    restart: unless-stopped

volumes:
  node-red-data:

networks:
  node-red-net: