services:

####################HASS
  home_assistant:
    container_name: home_assistant
    image: "homeassistant/home-assistant:latest"
    volumes:
      - /home/r0oland/docker/data/homeassistant_data:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
      interval: 120s
      timeout: 10s
      retries: 3
    depends_on:
      - mosquitto
      - node-red
      - esphome
      - tasmoadmin
      - grafana

################### Node Red
  node-red:
    container_name: node_red
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 1880:1880
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data
    restart: unless-stopped

###################TASMOADMIN
  tasmoadmin:
    container_name: tasmoadmin
    image: raymondmm/tasmoadmin
    ports:
      - 9999:80
    volumes:
      - /home/r0oland/docker/data/tasmoadmin_data:/data
    restart: unless-stopped


###################
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    network_mode: host
    restart: unless-stopped
    volumes:
      - /home/r0oland/docker/data/mosquitto_data/data:/mosquitto/data
      - /home/r0oland/docker/data/mosquitto_data/log:/mosquitto/log
      - /home/r0oland/docker/data/mosquitto_data/config:/mosquitto/config

###################
  esphome:
    image: esphome/esphome
    volumes:
      - /home/r0oland/docker/data/espHome_data:/config:rw
      # Use local time for logging timestamps
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    restart: unless-stopped  

###################
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - /home/r0oland/docker/data/influxData:/var/lib/influxdb2:rw
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

###################
  chronograf:
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}

###################
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - /home/r0oland/docker/data/grafana:/var/lib/grafana
    depends_on:
      - influxdb
      - chronograf
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

###################
  glances:
    image: nicolargo/glances:latest-full
    restart: always
    ports:
      - "61208:61208"
    environment:
      GLANCES_OPT: "-w" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - /home/r0oland/docker/data/glances:/glances/conf/glances.conf
    pid: "host"

# Volumes ======================================================================
volumes:
  tasmoadmin_data:
  node-red-data:
  chronograf-storage:

networks:
  node-red-net: