homeassistant: true
frontend: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.178.3:1883
serial:
  port: /dev/ttyACM0
advanced:
  pan_id: 5839
  ext_pan_id:
    - 124
    - 35
    - 245
    - 19
    - 169
    - 170
    - 179
    - 161
  channel: 15
  network_key:
    - 86
    - 8
    - 174
    - 164
    - 28
    - 109
    - 205
    - 133
    - 209
    - 195
    - 159
    - 208
    - 155
    - 204
    - 164
    - 81
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0x70ac08fffe96c3f7':
    friendly_name: '0x70ac08fffe96c3f7'
  '0x70ac08fffe96c674':
    friendly_name: GU10_office_2
  '0x70ac08fffe96bc08':
    friendly_name: GU10_office_1
  '0x70ac08fffe97a9a3':
    friendly_name: '0x70ac08fffe97a9a3'
  '0x70ac08fffe96c3db':
    friendly_name: '0x70ac08fffe96c3db'
  '0x94deb8fffe314483':
    friendly_name: '0x94deb8fffe314483'
